#!/bin/bash -x

mkdir -p xcat-core-svn
pushd xcat-core-svn
first=true
while ! git svn info || [[ $first == 'true' ]]
do
	first=false
	git svn clone \
	    -Txcat-core/trunk \
	    -bxcat-core/branches \
	    -txcat-core/tags \
	    http://xcat.svn.sourceforge.net/svnroot/xcat .
done
BRANCHES=$(git branch -a | grep remotes | grep -v tags | cut -d'/' -f2- | sort -r)
TAGS=$(git branch -a | grep remotes | grep tags | cut -d'/' -f2- | sort -r)
git remote add origin git@github.com:dmlb2000/xcat-core.git
for branch in $BRANCHES
do
	git push -u origin $branch
done
for tag in $TAGS
do
	git checkout $tag
	git tag $tag -m "${tag/tags\//}"
done
git push --tags
popd
